// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Authentication API": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/rymccue/golang-auth-microservice/design
// --out=$(GOPATH)/src/github.com/rymccue/golang-auth-microservice
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// LoginAuthenticationContext provides the authentication login action context.
type LoginAuthenticationContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *LoginPayload
}

// NewLoginAuthenticationContext parses the incoming request URL and body, performs validations and creates the
// context used by the authentication controller login action.
func NewLoginAuthenticationContext(ctx context.Context, r *http.Request, service *goa.Service) (*LoginAuthenticationContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := LoginAuthenticationContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *LoginAuthenticationContext) OK(r *Token) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.token+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *LoginAuthenticationContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *LoginAuthenticationContext) InternalServerError() error {
	ctx.ResponseData.WriteHeader(500)
	return nil
}

// RegisterAuthenticationContext provides the authentication register action context.
type RegisterAuthenticationContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *RegisterPayload
}

// NewRegisterAuthenticationContext parses the incoming request URL and body, performs validations and creates the
// context used by the authentication controller register action.
func NewRegisterAuthenticationContext(ctx context.Context, r *http.Request, service *goa.Service) (*RegisterAuthenticationContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := RegisterAuthenticationContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *RegisterAuthenticationContext) OK(r *Token) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.token+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *RegisterAuthenticationContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *RegisterAuthenticationContext) InternalServerError() error {
	ctx.ResponseData.WriteHeader(500)
	return nil
}
