// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Authentication API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/rymccue/golang-auth-microservice/design
// --out=$(GOPATH)/src/github.com/rymccue/golang-auth-microservice
// --version=v1.2.0-dirty

package app
